### ISSUE TITLE
Patch: Implement export of "Score".

### ISSUE THREAD

**Issue by aspell-helper** [GNUAspell/aspell#365]
**Ethan Bradford *<ethanrbradford\@sf>* created a patch on 2006-05-17 05:05:19 UTC**
*(Orig. from https://sourceforge.net/p/aspell/patches/134)*

I added API calls to export the "score" for each
suggestion.  The score is the "distance" of a
suggestion from the original word.  This can be used to
resort suggestions for a calling program which knows
something more about the words.

Here's the diff from the manual:

\--- reference/aspell/aspell\_0\_60/manual/aspell.texi   
2006-05-05 09:36:09.074874000 -0700
+++ aspell.texi    2006-05-16 16:49:01.891079000 -0700
@@ -2197,7 +2197,7 @@

@var\{word\}, @var\{size\}\);
AspellStringEnumeration \* elements =
aspell\_word\_list\_elements\(suggestions\);
const char \* word;
-while \( \(word =
aspell\_string\_enumeration\_next\(aspell\_elements\)\) \!= NULL \)
+while \( \(word =
aspell\_string\_enumeration\_next\(elements\)\) \!= NULL \)
@\{
// add to suggestion list
@\}
@@ -2206,7 +2206,30 @@

Notice how @code\{elements\} is deleted but
@code\{suggestions\} is not.
The value returned by @code\{suggestions\} is only valid
to the next
-call to @code\{suggest\}.  Once a replacement is made the
+call to @code\{suggest\}.
\+
+If you want to sort the Aspell words by some
additional criterion before
+presenting them, you should also take into account the
\`\`score'' that
+Aspell used to sort them.  The score gives the
\`\`distance'' of the
+suggestion from the original, with increasing scores
giving increasing
+distances.  To cycle through a list of suggestions
with scores,
+instead of the above example, copy this code:
+@smallexample
+AspellSuggestionList \* suggestions =
aspell\_speller\_scored\_suggest\(
\+                                                     
spell\_checker,
\+                                                     
@var\{word\}, @var\{size\}\);

+AspellSuggestionEnumeration \* elements =
\+                             
aspell\_suggestion\_list\_elements\(suggestions\);
+const AspellSuggestion \* sugg;
+while \( \(sugg =
aspell\_suggestion\_enumeration\_next\(elements\)\) \!= NULL \)
+@\{
\+  // Add to suggestion list sugg->word, of length
sugg->word\_len, and
\+  // with score sugg->score.
+@\}
+delete\_aspell\_suggestion\_enumeration\(elements\);
+@end smallexample
\+
+Once a replacement is made the
@code\{store\_repl\} method should be used to communicate
the replacement
pair back to the spell checker \(for the reason,
@pxref\{Notes on
Storing Replacement Pairs\}\).  Its usage is as follows:

**Comment by kwhumphreys** [comment]
patches are missing the files:
Only in ./common: suggestion.hpp
Only in ./Common: suggestion_enumeration.hpp
Only in ./common: suggestion_list.hpp
Only in ./lib: suggestion_enumeration-c.cpp
Only in ./lib: suggestion_list-c.cpp

**Comment by kevina** [comment]
@kwhumphreys this is a very very old report imported from sourceforge.  If you can't use the patch see if you can find what you need at https://sourceforge.net/p/aspell/patches/134.  You can also try and email the author directly via his sourceforge email address.  If the patch is still unusable for you there is not much I can do.  If you can figure out the problem please attach a better patch or even better create a p.r.

**Comment by robvanderg** [comment]
I was interested in the same thing.
I e-mailed Ethan to request the files, but in case he does not respond I created a very ugly patch.

This adds 4 characters to each candidate, a ':' followed by three numbers that report on the score used for this candidate. It can be used in pipeline made as well as in the API (you just need to extract the last 4 characters from a word). 
[asp-score-patch.txt](https://github.com/GNUAspell/aspell/files/827816/asp-score-patch.txt)

Note that this is an untested patch, and is a very dirty workaround. But it might just help you out

**Comment by kwhumphreys** [comment]
Thanks @robvanderg , I'll try it out.
I contacted Ethan, but the code is long gone, which is a shame after everything had been reviewed by @kevina 
It may be straightforward to recreate suggestion_list and suggestion_enumeration based on other list/enumeration files, but my C++ is very rusty.

**Comment by kwhumphreys** [comment]
Thanks @robvanderg. A slightly less ugly version:
[score.patch.txt](https://github.com/GNUAspell/aspell/files/835191/score.patch.txt)

**Comment by kevina** [comment]
@kwhumphreys @robvanderg note that some of those files are automatically generated.  If you have not already apply this to the git version and run `./autogen` or at least `perl mk-src.pl`.  That may create the missing files.  Sorry or missing this earlier.

**Comment by kwhumphreys** [comment]
Thanks @kevina. Yes, the missing files are autogenerated and:
`./maintainer/autogen; ./configure; ./make`
builds ok.
So Ethan's patch file is fine (with a couple of Copyright dates updated)

**Comment by kwhumphreys** [comment]
updated version of Ethan's patch to add a Makefile.am change
[aspell-0.60.6.1.patch.txt](https://github.com/GNUAspell/aspell/files/839696/aspell-0.60.6.1.patch.txt)

**Comment by kwhumphreys** [comment]
PR against latest version now at https://github.com/GNUAspell/aspell/pull/524
