### ISSUE TITLE
Edit distance: "anyhting" not corrected

### ISSUE THREAD

**Issue by aspell-helper** [GNUAspell/aspell#369]
**Ethan Bradford *<ethanrbradford\@sf>* created a bug report on 2006-06-06 00:09:14 UTC**
*(Orig. from https://sourceforge.net/p/aspell/bugs/188)*

The proposed list \(in English\) for "anyhting" goes all
the way down to "unhinge" and "Antoine", but doesn't
include "anything", which has a single transposition.

Something is failing majorly in the "edit distance" or
"score" calculation.

**Comment by kevina** [comment]
Typo's are now generally first in Aspell 0.60.8.  Closing.
