### ISSUE TITLE
repeatable core dump while checking file

### ISSUE THREAD

**Issue by aspell-helper** [GNUAspell/aspell#493]
**James K. Lowden *<jklowden\@sf>* created a bug report on 2011-12-18 21:50:30 UTC**
*(Orig. from https://sourceforge.net/p/aspell/bugs/253)*

The failed command is "aspell -c README".  \("aspell list < README" works.\)

$ gdb -c aspell.core $\(which aspell\)
GNU gdb 6.5
...
Core was generated by \`aspell'.
Program terminated with signal 11, Segmentation fault.
\#&#8203;0  0x00007f7ffcfd18e9 in fclose \(\) from /usr/lib/libc.so.12
\(gdb\) bt
\#&#8203;0  0x00007f7ffcfd18e9 in fclose \(\) from /usr/lib/libc.so.12
\#&#8203;1  0x0000000000425189 in std::vector<acommon::String, std::allocator<acommon::String> >::\_M\_fill\_insert \(\)
\[Higher frames have no symbols.  I can produce a better bt if you cannot reproduce the results.\]

Input file:  http://downloads.kergis.com/README

$ aspell --version
@\(\#\) International Ispell Version 3.1.20 \(but really Aspell 0.60.6\)

$ uname -a         
NetBSD oak.schemamania.org 5.0.2 NetBSD 5.0.2 \(GENERIC\) \#&#8203;0: Sat Feb  6 13:44:19 UTC 2010  builds@b8.netbsd.org:/home/builds/ab/netbsd-5-0-2-RELEASE/amd64/201002061851Z-obj/home/builds/ab/netbsd-5-0-2-RELEASE/src/sys/arch/amd64/compile/GENERIC amd64

$ file README
README: ISO-8859 English text

$ locale
LANG=""
LC\_CTYPE="C"
LC\_COLLATE="C"
LC\_TIME="C"
LC\_NUMERIC="C"
LC\_MONETARY="C"
LC\_MESSAGES="C"
LC\_ALL=""

**Comment by kevina** [comment]
I _think_ this is fixed.  I am no longer able to download the file so I can't verify.
