### ISSUE TITLE
aspell deletes symlinks - intentional?

### ISSUE THREAD

**Issue by aspell-helper** [GNUAspell/aspell#511]
**Sylwester Arabas *<slayoo\@sf>* created a bug report on 2013-03-19 18:45:03 UTC**
*(Orig. from https://sourceforge.net/p/aspell/bugs/266)*

Hello,

If aspell is pointed to a symlink it deletes it after checking spelling and creates a copy of the file pointed by the symlink. Is it intentional??? If so, at least a warning should be issued. It's an easy way to unintentionally spread different file versions around :\(

HTH,
Sylwester

**Comment by kevina** [comment]
Duplicate of #501.
