### ISSUE TITLE
Static initialization order fiasco

### ISSUE THREAD

**Issue by aspell-helper** [GNUAspell/aspell#512]
**Dhyanesh Damania *<ddamania\@sf>* created a bug report on 2013-05-27 09:37:28.647000 UTC**
*(Orig. from https://sourceforge.net/p/aspell/bugs/267)*

There is static initialization order fiasco while creating GlobalCacheBase. The global_cache_lock static variable may not be initialized when GlobalCacheBase is constructed.

```
static StackPtr<Mutex> global_cache_lock(new Mutex);
```

One of the instances where this is possible is from typo_edit_dist.cpp

```
static GlobalCache<TypoEditDistanceInfo> typo_edit_dist_info_cache("keyboard");
```

This was found by AddressSanitizer:

https://code.google.com/p/address-sanitizer/

**Comment by kevina** [comment]
Fixed in commit 0192b59f62c882eda40beee644f06756eb718365.
