### ISSUE TITLE
Incorporate bibliography in spell checking

### ISSUE THREAD

**Issue by aspell-helper** [GNUAspell/aspell#516]
**Diego M *<diego898\@sf>* created a feature request on 2015-10-20 22:02:20.916000 UTC**
*(Orig. from https://sourceforge.net/p/aspell/feature-requests/73)*

When spell checking latex documents, there should be some way to incorporate information from a bibliography. That way names that are in the bibliography are ignored when spell checking.

**Comment by kevina** [comment]
Parsing a bibliography is outside the scope of Aspell.  Aspell 0.60.8 has a new option `--add|rem-wordlists` that will allow you to easily add extra words when spell checking.
