### ISSUE TITLE
Please support markdown

### ISSUE THREAD

**Issue by RobertHenry6bev** [GNUAspell/aspell#536]
Please support markdown as a known language.  Yeah, there are a lot of dialects.  I'm primarily interested in it ignoring  stuff inside ``` code fences ```

**Comment by hrabbey** [comment]
It looks like the [pyspelling wrapper](https://github.com/facelessuser/pyspelling) supports markdown, but I agree that it would be nice as a aspell filter.

**Comment by kevina** [comment]
Sorry for the very long delay.  This is implemented in #558 and should be in Aspell 0.60.8.

**Comment by RobertHenry6bev** [comment]
Thank you!

**Comment by kevina** [comment]
> Thank you!

Your welcome.  Please test it out and let me know if it works for you.
