### ISSUE TITLE
Add irony mark "⸮" to punctuation.

### ISSUE THREAD

**Issue by kierun** [GNUAspell/aspell#538]
How can I add the [irony mark](https://en.wikipedia.org/wiki/Irony_punctuation#Irony_mark) as an end of sentence marker?

This might be either related to or blocked by [411](https://github.com/GNUAspell/aspell/issues/411)

**Comment by kevina** [comment]
Is there a reason you want to do this?

Aspell as a spell checker does not really care about sentence structure just individual words.  It also ignored `.` and `?`.

**Comment by kierun** [comment]
> Is there a reason you want to do this?

Yes, otherwise works like "hello⸮" are labelled as misspelled.

**Comment by kevina** [comment]
How are you using Aspell?.   Just like '?', The '⸮' is not a letter, so it should not become part of the word when the string is tokenized.  Does "hello?" cause a problem for you?

**Comment by kierun** [comment]
Hum… I opened this because of the signal desktop app where spell checking was highlighting works ending with ⸮. However, I just tried it and it seems to be working as you describe it.

Harrumph. I am happy to ascribe this to an error between keyboard and floor. ☺
