### ISSUE TITLE
version.cpp is supposed to be included in aspell/prog/aspell.cpp header declaration.

### ISSUE THREAD

**Issue by Pavel-Sayekat** [GNUAspell/aspell#543]
aspell/common/version.cpp is supposed to be included in aspell/prog/aspell.cpp header declaration as the aspell_version_string() function is defined in the aspell/common/version.cpp and called from  aspell/prog/aspell.cpp.

**Comment by Pavel-Sayekat** [comment]
I have merged the issue into the immediate previous issue.

**Comment by kevina** [comment]
I am assuming this is related to #542.  Closing for now.  If you still have a problem after following the instructions in README.md please reopen this issue.
