### ISSUE TITLE
Disable personal dictionary

### ISSUE THREAD

**Issue by m3gat0nn4ge** [GNUAspell/aspell#545]
Hi,

I tried to disable the personal dictionary using 'personal /dev/null' in the conf file, however at times aspell will hang trying to obtain a write lock on /dev/null:

fcntl(5, F_SETLKW, {l_type=F_WRLCK, l_whence=SEEK_SET, l_start=0, l_len=0}

Are there any other methods to disable the personal dictionary?.. I couldn't find anything in the man page

many thanks

**Comment by kevina** [comment]
You can use `--dont-use-other-dicts` to disable the personal and session dictionary.  With this option any commands to add to those respective dictionary will be ignored.  This option is not documented in the man page or info docs but is shown when using `aspell --help`.

**Comment by m3gat0nn4ge** [comment]
Thanks @kevina ..  so if I am using "extra-dicts <filename>" in my conf file ... will the --dont-use-other-dicts option affect that?

**Comment by kevina** [comment]
No.  I just tested it and that option will not effect any extra dictionaries explicitly specified.
