### ISSUE TITLE
English: naïve

### ISSUE THREAD

**Issue by shawnl** [GNUAspell/aspell#548]
`naïve`, not just `naive`.

Also, `piñata`, not just `pinata`

**Comment by kevina** [comment]
Please report this to https://github.com/en-wl/wordlist/issues.

Also see https://github.com/en-wl/wordlist/issues/139.

**Comment by kevina** [comment]
See https://github.com/en-wl/wordlist/issues/139 and https://github.com/en-wl/wordlist/issues/139#issuecomment-510711757.
