### ISSUE TITLE
Update Uzbek dictionary

### ISSUE THREAD

**Issue by bmansurov** [GNUAspell/aspell#577]
Update the Uzbek dictionary. It contains 244,145 words now as opposed to the previous count of 97,000. The file has been zipped, because Github doesn't allow uploading tar.bz2 files.

[aspell6-uz-0.7-0.tar.bz2.zip](https://github.com/GNUAspell/aspell/files/3639236/aspell6-uz-0.7-0.tar.bz2.zip)

**Comment by kevina** [comment]
Thank you for your contribution.  As a policy I do not accept updates from someone other than the original maintainer.  

I take it you are, Bahodir Mansurov.  Please reach out to the original maintainer Mashrab Kuvatov and get his approval for the update.  Alternatively if Debian updates there package to yours I will do the same.

Let's keep this issue open but it better to coordinate thing via the aspell-devel (https://lists.gnu.org/mailman/listinfo/aspell-devel) mailing list.

**Comment by bmansurov** [comment]
Hi, thanks for the quick response. I've sent an email to the original maintainer. Hopefully he'll comment here.

**Comment by kmashrab** [comment]
Thanks for your work, Bahodir. We need a source-file i.e. world-list first. I will host it here on GitHub. Once we have a world-list, we can generate a dictionary for other spell-checkers, too.

Please let's move further discussion off-line.

**Comment by bmansurov** [comment]
Thanks. For posterity, here's the repository: https://github.com/kmashrab/uzbek-wordlist

**Comment by kevina** [comment]
Okay thanks.  I am closing this issue.  If you have an update ready that you want me to upload please create a new issue.  Note that in order for me to upload it it needs to be created with the "proc" script from the aspell-lang package: https://github.com/GNUAspell/aspell-lang.
