### ISSUE TITLE
Aspell .suggest not reciprocal? 

### ISSUE THREAD

**Issue by ndvbd** [GNUAspell/aspell#589]
When doing `.suggest('patients')`, I don't see `patience` in the list.
But when doing `.suggest('patience')`, I do see `patients` in the list.

Why isn't it reciprocal?``

**Comment by ndvbd** [comment]
Anybody home?

**Comment by kevina** [comment]
Aspell makes no such guarantee.  There is a slight chance it is a bug, but it is unlikely.

**Comment by ndvbd** [comment]
@kevina, maybe you can check it? Since editdistance(a,b) = editdistance(b,a) it should be the same, shouldn't it? Do you see the same symptom on your end?
