### ISSUE TITLE
How to stop Aspell forcing console colours white text on black background

### ISSUE THREAD

**Issue by PBreeze** [GNUAspell/aspell#596]
Aspell seems to force the console to switch to white text on a black background, whatever default console colour scheme has been chosen.  (It also tries to do the same with ConEmu with varying results.)  Is there any way of preventing this, and allowing the default console colours to appear in the Aspell console?

**Comment by kevina** [comment]
This is likely unintentional.  I will need to look into what the ncurses code is doing.  Patches welcome.

**Comment by kevina** [comment]
@PBreeze I can not reproduce this, what version of Aspell and what terminal emulator are you using?

**Comment by PBreeze** [comment]
I am using v 0.50.3 with MSDOS under Windows 7 (Actually VDOS which is a teminal emulator for using XYWrite with 64 bit windows).

**Comment by kevina** [comment]
I am afraid I no longer support Aspell 0.50.  Sorry.
