### ISSUE TITLE
cannot install aspell with only english dictionary

### ISSUE THREAD

**Issue by albertparedandan** [GNUAspell/aspell#597]
I am trying to install aspell on MacOS Catalina. But can't seem to find a way to only install the english dictionary since i don't need the others. i have tried

`brew install aspell aspell-en`
`brew install aspell --with-lang-en`

both does not work and brew says formula does not exists

**Comment by kevina** [comment]
I do not directly support Homebrew please see https://docs.brew.sh/Troubleshooting for help.
