### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by adamsmd** [GNUAspell/aspell#600]
The following triggers a memory leak in `aspell` at a rate of approximately 1GB per minute (which is approximately 10,000 lines of input).

```
perl -e 'for $x1 ("A".."Z") { for $x2 ("A".."Z") { for $x3 ("A".."Z") { print STDERR "$x1$x2$x3\n"; for $x4 ("A".."Z") { for $x5 ("A".."Z") { print "$x1$x2$x3$x4$x5\n" } } } } }' | aspell -a >/dev/null
```

The following also triggers a memory leak in `aspell` but it is a much slower leak.

```
perl -e 'while (1) { print "QWETDSFDG\n" } '|aspell -a >/dev/null
```

This is for Aspell 0.60.8 on Ubuntu 20.04.

**Comment by ndvbd** [comment]
What's the status? I am seeing a leak with running this using the python wrapper:

```
import aspell
spellChecker = aspell.Speller('lang', 'en')
for i in range(100000000):
	result = spellChecker.suggest("TNKLR")
```
