### ISSUE TITLE
Man page: html-skip and sgml-skip options incorrectly documented 

### ISSUE THREAD

**Issue by fallax** [GNUAspell/aspell#602]
On the man page, the following options are incorrectly documented as relating to _attributes_, instead of _tags_:

``` 
        --add-html-skip=<list>, --rem-html-skip=<list>
              Add or remove a list of HTML attributes to always skip while spell checking.
```
and
```
        --add-sgml-skip=<list>, --rem-sgml-skip=<list>
              Add or remove a list of SGML attributes to always skip while spell checking.
```

I imagine this mistake arose because html-check and sgml-check options relate to attributes, but these -skip ones are for tags instead.

The documentation elsewhere in the project appears to be correctly referring to tags not attributes -https://github.com/GNUAspell/aspell/blob/770c32f17da6805cffa777b20278b02dd392ddeb/manual/aspell.texi (line 1213).

**Comment by kevina** [comment]
Thanks for pointing this out, it looks like it was fixed in e8eb74793bce4fab381cc40f1c60f9572a99fb94.
