### ISSUE TITLE
English: ideation

### ISSUE THREAD

**Issue by Stebalien** [GNUAspell/aspell#605]
Definition: The formation of ideas/concepts.
Frequency: 4 stars, 1.2 newness, 1.1pm: http://app.aspell.net/lookup?dict=en_US;words=ideation

**Comment by kevina** [comment]
This is the issue tracker for GNU Aspell itself, not the dictionary it uses.  Please post to https://github.com/en-wl/wordlist/issues and close this issue once done.

**Comment by Stebalien** [comment]
(I really should have known better, thanks!)

**Comment by kevina** [comment]
(and I almost replied, until I discovered that @biljir wasn't completing :) )
