### ISSUE TITLE
Replace "satysfiability" with "satisfiability"

### ISSUE THREAD

**Issue by salutis** [GNUAspell/aspell#614]
I am not sure if this is the right place to report bugs in the English dictionary for Aspell.

**Comment by Eason0210** [comment]
Hi @salutis , If you are using Emacs with flyspell, you can add "satisfiability" to personal dictionary.

**Comment by salutis** [comment]
@Eason0210 I know, and I did. I was curious where to contribute to the official dictionary. I think it could use some help...

**Comment by kevina** [comment]
This is not the place to report missing words for any dictionary.  The website for the official dictionary for Aspell is http://wordlist.aspell.net/ and it's GitHub repo is https://github.com/en-wl/wordlist.

**Comment by salutis** [comment]
@kevina Thank you so much. I tried but could not find those sources myself.
