### ISSUE TITLE
Request HTML spellcheck attribute

### ISSUE THREAD

**Issue by ryma2fhir** [GNUAspell/aspell#634]
There is an HTML spellcheck attribute to specify whether the element is to have its spelling and grammar checked or not. It would be very helpful if Aspell could work with this. 

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/spellcheck

**Comment by kevina** [comment]
Is there any indication that this is used to actually mark parts of the document that should or should not be spell checked?  The documentation you pointed to seams to indicate it a hint for browsers on if the user input should be checked and there is no indication that it is used to mark what parts of the html document itself should or should not be spell checked.
