### ISSUE TITLE
Confusion regarding en-GB-ize?

### ISSUE THREAD

**Issue by haji-ali** [GNUAspell/aspell#638]
As far as I understand, the `en-GB-ize` dictionary should accept and suggest words ending with `-ize` instead of `-ise`, but this doesn't seem to be the case in the latest version of aspell.

```
> aspell dump dicts | grep en_GB-ize
en_GB-ize
en_GB-ize-w_accents
en_GB-ize-wo_accents

> echo "categorize authorize randomize" | aspell -a -l en_GB-ize

@(#) International Ispell Version 3.1.20 (but really Aspell 0.60.8)
& categorize 6 0: categorise, categories, categorised, categorises, category's, category
& authorize 12 11: authorise, authorial, authoring, authority, authoress, authored, authorities, authors, author's, reauthorise, euthanize, authority's
& randomize 5 21: randomise, randomised, randomises, randoms, random
```

Is this expected? The US dictionary seems to work as expected:

```
> echo "categorize authorize randomize" | aspell -a -l en_US    
@(#) International Ispell Version 3.1.20 (but really Aspell 0.60.8)
*
*
*
```

**Comment by kevina** [comment]
Hi,  The "-ize" is not recognized as part of the language code.  The most straightforward way to specify a dictionary is to use the '-d' option.  Foe example:

```
> echo "categorize authorize randomize" | aspell -a -d en_GB-ize
@(#) International Ispell Version 3.1.20 (but really Aspell 0.60.8)
*
*
*
```

Please see http://aspell.net/man-html/How-Aspell-Selects-an-Appropriate-Dictionary.html for ways to specify the "ize" variant by default for en_GB.
