### ISSUE TITLE
Aspell and the word "rj45"

### ISSUE THREAD

**Issue by klapvogn** [GNUAspell/aspell#649]
Hi,

I have an error when I try to do : `echo -e "*rj45\n#" | aspell -a`

I get:
```
@(#) International Ispell Version 3.1.20 (but really Aspell 0.60.8)
Error: The word "rj45" is invalid. The character '4' (U+34) may not appear in the middle of a word.
```

Is there something I can do to make it work?

**Comment by kevina** [comment]
Hi, unfortunately Aspell does not support numbers as part of a word.

By creating a custom charset, you can force Aspell to accept all digits as part of a word but then all numbers will be flagged as misspelling.  It is not something I would recommend.

**Comment by kevina** [comment]
Note that if you are using Aspell 0.60.8 or newer you can also set the config option `validate-words` to false to allow the word into the personal dictionary.  For example `aspell --dont-validate-words -a`.  However once this word is in your personal dictionary you will need to always have this option set.  Also, note that you will only be able to check the word "rj45" if the application is using the C API.  If it is using the pipe interface the "45" part will not be recognized as part of the word and Aspell will instead check for "rj".
